### ISSUE TITLE
Add support for integrating publishing credentials

### ISSUE THREAD

**Issue by JamesDawson** [endjin/Endjin.RecommendedPractices.GitHubActions#4]
Out standardised build process supports publishing packages of several formats:

```[tasklist]
### Tasks
- [ ] https://github.com/endjin/Endjin.RecommendedPractices.GitHubActions/issues/9
- [ ] https://github.com/endjin/Endjin.RecommendedPractices.GitHubActions/issues/10
- [ ] https://github.com/endjin/Endjin.RecommendedPractices.GitHubActions/issues/11
- [ ] https://github.com/endjin/Endjin.RecommendedPractices.GitHubActions/issues/12
```

This task is to develop a consistent and maintainable approach for supplying these scenarios with the credentials they require.
